// <auto-generated />
using HalelkeherCiwerecawqal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HalelkeherCiwerecawqal.Migrations
{
    [DbContext(typeof(KekairwuceeYernellijewhebere))]
    partial class KekairwuceeYernellijewhebereModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("HalelkeherCiwerecawqal.ResourceModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceFileDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceSign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResourceModel");
                });
#pragma warning restore 612, 618
        }
    }
}
