<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Direct3D9" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.22.0" />
    <PackageReference Include="Silk.NET.DXGI" Version="2.22.0" />
  </ItemGroup>
</Project>
