// <auto-generated />
using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace JawjeleceeYairlubelhearrene.Properties;

[GeneratedCode("Manual", "1.0")]
public static class Resources
{
    private static readonly ResourceManager ResourceManagerInstance = new("JawjeleceeYairlubelhearrene.Properties.Resources", typeof(Resources).Assembly);

    public static ResourceManager ResourceManager => ResourceManagerInstance;

    public static CultureInfo? Culture { get; set; }

    private static string GetString(string name) => ResourceManager.GetString(name, Culture) ?? string.Empty;

    public static string AppTitle => GetString(nameof(AppTitle));
    public static string HeaderTitle => GetString(nameof(HeaderTitle));
    public static string HeaderSubtitle => GetString(nameof(HeaderSubtitle));
    public static string InputSectionTitle => GetString(nameof(InputSectionTitle));
    public static string DropHintTitle => GetString(nameof(DropHintTitle));
    public static string DropHintDescription => GetString(nameof(DropHintDescription));
    public static string BrowsePptButton => GetString(nameof(BrowsePptButton));
    public static string BrowseFfmpegButton => GetString(nameof(BrowseFfmpegButton));
    public static string OpenSpeechSectionTitle => GetString(nameof(OpenSpeechSectionTitle));
    public static string OpenSpeechApiKeyLabel => GetString(nameof(OpenSpeechApiKeyLabel));
    public static string ResourceIdLabel => GetString(nameof(ResourceIdLabel));
    public static string SpeakerLabel => GetString(nameof(SpeakerLabel));
    public static string OpenAiSectionTitle => GetString(nameof(OpenAiSectionTitle));
    public static string OpenAiApiKeyLabel => GetString(nameof(OpenAiApiKeyLabel));
    public static string OpenAiEndpointLabel => GetString(nameof(OpenAiEndpointLabel));
    public static string OpenAiModelLabel => GetString(nameof(OpenAiModelLabel));
    public static string OutputSectionTitle => GetString(nameof(OutputSectionTitle));
    public static string FfmpegPathLabel => GetString(nameof(FfmpegPathLabel));
    public static string OutputDirectoryLabel => GetString(nameof(OutputDirectoryLabel));
    public static string ActionSectionTitle => GetString(nameof(ActionSectionTitle));
    public static string GenerateButton => GetString(nameof(GenerateButton));
    public static string OpenOutputFolderButton => GetString(nameof(OpenOutputFolderButton));
    public static string StatusReady => GetString(nameof(StatusReady));
    public static string PreviewSectionTitle => GetString(nameof(PreviewSectionTitle));
    public static string PreviewPlaceholder => GetString(nameof(PreviewPlaceholder));
    public static string PlayButton => GetString(nameof(PlayButton));
    public static string PauseButton => GetString(nameof(PauseButton));
    public static string StopButton => GetString(nameof(StopButton));
    public static string SlidesSectionTitle => GetString(nameof(SlidesSectionTitle));
    public static string LogsSectionTitle => GetString(nameof(LogsSectionTitle));
    public static string NoSlidesPlaceholder => GetString(nameof(NoSlidesPlaceholder));
    public static string SpeakerPreviewFormat => GetString(nameof(SpeakerPreviewFormat));
    public static string SlideHeaderFormat => GetString(nameof(SlideHeaderFormat));
    public static string SlideTextLabel => GetString(nameof(SlideTextLabel));
    public static string GeneratedScriptLabel => GetString(nameof(GeneratedScriptLabel));
    public static string ValidationSelectPpt => GetString(nameof(ValidationSelectPpt));
    public static string ValidationOpenSpeechApiKey => GetString(nameof(ValidationOpenSpeechApiKey));
    public static string ValidationResourceId => GetString(nameof(ValidationResourceId));
    public static string ValidationSpeaker => GetString(nameof(ValidationSpeaker));
    public static string ValidationOpenAiApiKey => GetString(nameof(ValidationOpenAiApiKey));
    public static string ValidationOpenAiEndpoint => GetString(nameof(ValidationOpenAiEndpoint));
    public static string ValidationOpenAiModel => GetString(nameof(ValidationOpenAiModel));
    public static string ValidationFfmpegPath => GetString(nameof(ValidationFfmpegPath));
    public static string ValidationOutputDirectory => GetString(nameof(ValidationOutputDirectory));
    public static string ComFailureHint => GetString(nameof(ComFailureHint));
    public static string GenerationCompletedFormat => GetString(nameof(GenerationCompletedFormat));
    public static string DroppedFileInvalid => GetString(nameof(DroppedFileInvalid));
}
