//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightTextEditorPlus.Resources.Wpf {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightTextEditorPlus.Resources.Wpf.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无效的 Unicode 字符范围。 的本地化字符串。
        /// </summary>
        internal static string FontFamilyMapItem_InvalidUnicodeRange {
            get {
                return ResourceManager.GetString("FontFamilyMapItem_InvalidUnicodeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态配置属性“{0}”只允许设置一次。 的本地化字符串。
        /// </summary>
        internal static string StaticConfigurationPropertyMultipleSettingsException_PropertyHasAlreadyBeenSet {
            get {
                return ResourceManager.GetString("StaticConfigurationPropertyMultipleSettingsException_PropertyHasAlreadyBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只支持 Normal、Superscript、Subscript。当前传入值为 {0}。 的本地化字符串。
        /// </summary>
        internal static string TextEditor_SetFontVariantsOnlySupportsNormalSuperscriptSubscript {
            get {
                return ResourceManager.GetString("TextEditor_SetFontVariantsOnlySupportsNormalSuperscriptSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在布局的过程中触发立刻布局，可能出现无限递归并导致堆栈溢出。 的本地化字符串。
        /// </summary>
        internal static string TextEditorPlatformProvider_ReentrantEnsureLayoutUpdated {
            get {
                return ResourceManager.GetString("TextEditorPlatformProvider_ReentrantEnsureLayoutUpdated", resourceCulture);
            }
        }
    }
}
