@CairkerkugelLerehenalcaceenel_HostAddress = http://127.0.0.1:5123

GET {{CairkerkugelLerehenalcaceenel_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{CairkerkugelLerehenalcaceenel_HostAddress}}/
Accept: application/json