//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 个人信息数据库principalComputer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sql() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("个人信息数据库principalComputer.sql", typeof(sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 我们5月12日和小文去图书馆
        ///你周六9点和阿金聊天
        ///你8月4日和小焕吃大餐
        ///我们9月9日和小雪去骑行50公里
        ///你周三21点和小红去马场骑马
        ///我周五20点和菲菲去医院看医生
        ///我后天7点和凌霜华旅游
        ///你4月28日和湘林去图书馆
        ///我们1月12日和千湄举办生日派对
        ///我们2月29日和大军举办生日派对
        ///我们周日12点和丽丽唱歌
        ///我6月17日和小欢摄影
        ///你5月14日和阴露萍去图书馆
        ///我4月1日和建华买东西
        ///我4月27日和华诗吃大餐
        ///我们周五12点和李灵黛去马场骑马
        ///我们4月25日和飞哥去机场接机
        ///我10月30日和小超约会
        ///我4月12日和小唐吃大餐
        ///我们7月17日和华诗举办生日派对
        ///我们6月1日和丽丽约会
        ///我周三14点和水笙聊天
        ///我明天10点和静静旅游
        ///你2月30日和丁玲珑举办生日派对
        ///我周五7点和弟弟去骑行50公里
        ///你周三12点和文子摄影
        ///我们周日21点和敏敏姐唱歌
        ///我1月16日和建华旅游
        ///我们10月9日和文子逛街
        ///我1月29日和建华去马场骑马
        ///你周五14点和卫国旅游
        ///你7月30日和湘林摄影
        ///你7月2日和小慧买东西
        ///我4月5日和阴露萍唱歌
        ///你3月12日和小 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string incident {
            get {
                return ResourceManager.GetString("incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吃大餐
        ///逛街
        ///买东西
        ///看电影
        ///约会
        ///聊天
        ///去图书馆
        ///去机场接机
        ///去医院看医生
        ///入手新出的iphone
        ///旅游
        ///写作
        ///唱歌
        ///摄影
        ///去拔牙
        ///去公园放风筝
        ///举办生日派对
        ///去看演唱会
        ///去骑行50公里
        ///去马场骑马
        ///去高尔夫场打高尔夫
        ///去做美容
        /// 的本地化字符串。
        /// </summary>
        internal static string 事件 {
            get {
                return ResourceManager.GetString("事件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        /// 东城区 
        /// 西城区 
        /// 崇文区 
        /// 宣武区 
        /// 朝阳区 
        /// 丰台区 
        /// 石景山区 
        /// 海淀区 
        /// 门头沟区 
        /// 房山区 
        /// 通州区 
        /// 顺义区 
        /// 昌平区 
        /// 大兴区 
        /// 怀柔区 
        /// 平谷区 
        /// 密云县 
        /// 延庆县 
        ///
        /// 黄浦区 
        /// 卢湾区 
        /// 徐汇区 
        /// 长宁区 
        /// 静安区 
        /// 普陀区 
        /// 闸北区 
        /// 虹口区 
        /// 杨浦区 
        /// 闵行区 
        /// 宝山区 
        /// 嘉定区 
        /// 浦东新区 
        /// 金山区 
        /// 松江区 
        /// 青浦区 
        /// 南汇区 
        /// 奉贤区 
        /// 崇明县 
        ///
        /// 和平区 
        /// 河东区 
        /// 河西区 
        /// 南开区 
        /// 河北区 
        /// 红桥区 
        /// 塘沽区 
        /// 汉沽区 
        /// 大港区 
        /// 东丽区 
        /// 西青区 
        /// 津南区 
        /// 北辰区 
        /// 武清区 
        /// 宝坻区 
        /// 宁河县 
        /// 静海县 
        /// 蓟县 
        ///
        /// 万州区 
        /// 涪陵区 
        /// 渝中区 
        /// 大渡口区 
        /// 江北区 
        /// 沙坪坝区 
        /// 九龙坡区 
        /// 南岸区 
        /// 北碚区 
        /// 万盛区 
        /// 双桥区 
        /// 渝北区 
        /// 巴南区 
        /// 黔江区 
        /// 长寿区 
        /// 江津区 
        /// 合 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 城市 {
            get {
                return ResourceManager.GetString("城市", resourceCulture);
            }
        }
    }
}
