using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DotNetCampus.Storage.Analyzer;

[Generator(LanguageNames.CSharp)]
public class SaveInfoNodeParserGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 查找所有带有 SaveInfoContract 特性的类
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSaveInfoCandidate(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // 组合编译信息并生成代码
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsSaveInfoCandidate(SyntaxNode node)
    {
        // 查找带有特性的类声明
        return node is ClassDeclarationSyntax classDeclaration
            && classDeclaration.AttributeLists.Count > 0;
    }

    private static ClassInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // 检查是否继承自 SaveInfo
        if (!InheritsFromSaveInfo(classSymbol))
            return null;

        // 查找 SaveInfoContract 特性
        var contractAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "SaveInfoContractAttribute");

        if (contractAttribute == null)
            return null;

        // 获取特性中的名称参数
        var contractName = contractAttribute.ConstructorArguments.FirstOrDefault().Value?.ToString();
        if (string.IsNullOrEmpty(contractName))
            return null;

        // 获取所有带有 SaveInfoMember 特性的属性
        var properties = new List<PropertyInfo>();
        foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            var memberAttribute = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "SaveInfoMemberAttribute");

            if (memberAttribute == null)
                continue;

            var memberName = memberAttribute.ConstructorArguments.FirstOrDefault().Value?.ToString();
            if (string.IsNullOrEmpty(memberName))
                continue;

            properties.Add(new PropertyInfo
            {
                PropertyName = member.Name,
                PropertyType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                StorageName = memberName,
                IsNullable = member.Type.NullableAnnotation == NullableAnnotation.Annotated
            });
        }

        return new ClassInfo
        {
            ClassName = classSymbol.Name,
            Namespace = classSymbol.ContainingNamespace.ToDisplayString(),
            ContractName = contractName,
            Properties = properties
        };
    }

    private static bool InheritsFromSaveInfo(INamedTypeSymbol classSymbol)
    {
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.Name == "SaveInfo")
                return true;
            baseType = baseType.BaseType;
        }
        return false;
    }

    private static void Execute(Compilation compilation, IEnumerable<ClassInfo> classes, SourceProductionContext context)
    {
        if (!classes.Any())
            return;

        foreach (var classInfo in classes)
        {
            var source = GenerateNodeParser(classInfo);
            context.AddSource($"{classInfo.ClassName}NodeParser.g.cs", source);
        }
    }

    private static string GenerateNodeParser(ClassInfo classInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using DotNetCampus.Storage.Lib.Parsers;");
        sb.AppendLine("using DotNetCampus.Storage.Lib.Parsers.Contexts;");
        sb.AppendLine("using DotNetCampus.Storage.Lib.Parsers.NodeParsers;");
        sb.AppendLine("using DotNetCampus.Storage.Lib.SaveInfos;");
        sb.AppendLine("using DotNetCampus.Storage.Lib.StorageNodes;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        sb.AppendLine($"namespace {classInfo.Namespace};");
        sb.AppendLine();

        sb.AppendLine($"public partial class {classInfo.ClassName}NodeParser : SaveInfoNodeParser<{classInfo.ClassName}>");
        sb.AppendLine("{");
        
        // ContractAttribute 属性
        sb.AppendLine($"    public override SaveInfoContractAttribute ContractAttribute {{ get; }} = new SaveInfoContractAttribute(\"{classInfo.ContractName}\");");
        sb.AppendLine();

        // ParseCore 方法
        GenerateParseCore(sb, classInfo);
        sb.AppendLine();

        // DeparseCore 方法
        GenerateDeparseCore(sb, classInfo);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateParseCore(StringBuilder sb, ClassInfo classInfo)
    {
        sb.AppendLine("    protected override " + classInfo.ClassName + " ParseCore(StorageNode node, in ParseNodeContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        StorableNodeParserManager parserManager = context.ParserManager;");
        sb.AppendLine();
        sb.AppendLine("        // 决定不支持 init 的情况，这样才能更好地保留默认值");
        sb.AppendLine($"        var result = new {classInfo.ClassName}();");
        sb.AppendLine();
        sb.AppendLine("        if (node.Children is { } children)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var storageNode in children)");
        sb.AppendLine("            {");
        sb.AppendLine("                var currentName = storageNode.Name.AsSpan();");
        sb.AppendLine();

        foreach (var property in classInfo.Properties)
        {
            var propertyVarName = $"propertyNameFor{property.PropertyName}";
            sb.AppendLine($"                var {propertyVarName} = \"{property.StorageName}\";");
            sb.AppendLine($"                if (currentName.Equals({propertyVarName}, StringComparison.Ordinal))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var typeOf{property.PropertyName} = typeof({property.PropertyType});");
            sb.AppendLine($"                    var nodeParserFor{property.PropertyName} = parserManager.GetNodeParser(typeOf{property.PropertyName});");
            sb.AppendLine($"                    var valueFor{property.PropertyName} = nodeParserFor{property.PropertyName}.Parse(storageNode, context);");
            sb.AppendLine($"                    result.{property.PropertyName} = ({property.PropertyType}) valueFor{property.PropertyName};");
            sb.AppendLine("                }");
            sb.AppendLine();
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void GenerateDeparseCore(StringBuilder sb, ClassInfo classInfo)
    {
        sb.AppendLine("    protected override StorageNode DeparseCore(" + classInfo.ClassName + " obj, in DeparseNodeContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        StorableNodeParserManager parserManager = context.ParserManager;");
        sb.AppendLine();
        sb.AppendLine("        var storageNode = new StorageNode();");
        sb.AppendLine($"        const int saveInfoMemberCount = {classInfo.Properties.Count};");
        sb.AppendLine("        storageNode.Name = context.NodeName ?? TargetStorageName;");
        sb.AppendLine("        storageNode.Children = new List<StorageNode>(saveInfoMemberCount);");
        sb.AppendLine();
        sb.AppendLine("        DeparseNodeContext tempContext;");
        sb.AppendLine();

        foreach (var property in classInfo.Properties)
        {
            var propertyVarName = $"propertyNameFor{property.PropertyName}";
            sb.AppendLine($"        var {propertyVarName} = \"{property.StorageName}\";");
            sb.AppendLine($"        var typeOf{property.PropertyName} = typeof({property.PropertyType});");
            sb.AppendLine($"        var nodeParserFor{property.PropertyName} = parserManager.GetNodeParser(typeOf{property.PropertyName});");
            sb.AppendLine($"        object? valueFor{property.PropertyName} = obj.{property.PropertyName};");
            sb.AppendLine($"        if (valueFor{property.PropertyName} is not null)");
            sb.AppendLine("        {");
            sb.AppendLine("            tempContext = context with");
            sb.AppendLine("            {");
            sb.AppendLine($"                NodeName = {propertyVarName}");
            sb.AppendLine("            };");
            sb.AppendLine($"            var childNodeFor{property.PropertyName} = nodeParserFor{property.PropertyName}.Deparse(valueFor{property.PropertyName}, tempContext);");
            sb.AppendLine($"            storageNode.Children.Add(childNodeFor{property.PropertyName});");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        return storageNode;");
        sb.AppendLine("    }");
    }

    private class ClassInfo
    {
        public string ClassName { get; set; } = null!;
        public string Namespace { get; set; } = null!;
        public string ContractName { get; set; } = null!;
        public List<PropertyInfo> Properties { get; set; } = new();
    }

    private class PropertyInfo
    {
        public string PropertyName { get; set; } = null!;
        public string PropertyType { get; set; } = null!;
        public string StorageName { get; set; } = null!;
        public bool IsNullable { get; set; }
    }
}
