using AgentLib.ChatRoom.Model;

namespace AgentLib.ChatRoom.Tests.Model;

[TestClass]
public sealed class ChatRoomMessageTests
{
    [TestMethod]
    public void CreateSystem_ValidContent_ReturnsSystemMessageWithCorrectProperties()
    {
        const string content = "系统通知：角色发言失败";

        ChatRoomMessage message = ChatRoomMessage.CreateSystem(content);

        Assert.AreEqual(content, message.Content);
        Assert.AreEqual("系统", message.SenderRoleName);
        Assert.IsTrue(message.IsSystemMessage);
        Assert.IsFalse(message.IsHumanMessage);
        Assert.AreEqual(string.Empty, message.SenderRoleId);
        Assert.IsNotNull(message.MessageId);
        Assert.AreNotEqual(string.Empty, message.MessageId);
    }

    [TestMethod]
    public void CreateSystem_NullContent_ThrowsArgumentNullException()
    {
        Assert.ThrowsExactly<ArgumentNullException>(() => ChatRoomMessage.CreateSystem(null!));
    }

    [TestMethod]
    public void CreateSystem_EmptyContent_ReturnsMessageWithEmptyContent()
    {
        const string content = "";

        ChatRoomMessage message = ChatRoomMessage.CreateSystem(content);

        Assert.AreEqual(content, message.Content);
        Assert.AreEqual("系统", message.SenderRoleName);
        Assert.IsTrue(message.IsSystemMessage);
    }

    [TestMethod]
    public void CreateSystem_MessageId_IsAutoGenerated()
    {
        ChatRoomMessage message1 = ChatRoomMessage.CreateSystem("msg1");
        ChatRoomMessage message2 = ChatRoomMessage.CreateSystem("msg2");

        Assert.AreNotEqual(string.Empty, message1.MessageId);
        Assert.AreNotEqual(string.Empty, message2.MessageId);
        Assert.AreNotEqual(message1.MessageId, message2.MessageId);
    }

    [TestMethod]
    public void CreateSystem_Timestamp_IsRecent()
    {
        DateTimeOffset before = DateTimeOffset.Now;

        ChatRoomMessage message = ChatRoomMessage.CreateSystem("test");

        // Allow tolerance due to DateTimeOffset precision
        TimeSpan tolerance = TimeSpan.FromMilliseconds(100);
        Assert.IsGreaterThanOrEqualTo(before - tolerance, message.Timestamp);
        Assert.IsLessThanOrEqualTo(DateTimeOffset.Now + tolerance, message.Timestamp);
    }

    [TestMethod]
    public void CreateHuman_ValidContentAndRoleIdAndRoleName_ReturnsHumanMessageWithCorrectProperties()
    {
        const string content = "大家好";
        const string humanRoleId = "human-001";
        const string humanRoleName = "张三";

        ChatRoomMessage message = ChatRoomMessage.CreateHuman(content, humanRoleId, humanRoleName);

        Assert.AreEqual(content, message.Content);
        Assert.AreEqual(humanRoleId, message.SenderRoleId);
        Assert.AreEqual(humanRoleName, message.SenderRoleName);
        Assert.IsTrue(message.IsHumanMessage);
        Assert.IsFalse(message.IsSystemMessage);
        Assert.IsNotNull(message.MessageId);
        Assert.AreNotEqual(string.Empty, message.MessageId);
    }

    [TestMethod]
    public void CreateHuman_NullContent_ThrowsArgumentNullException()
    {
        Assert.ThrowsExactly<ArgumentNullException>(
            () => ChatRoomMessage.CreateHuman(null!, "roleId", "roleName"));
    }

    [TestMethod]
    public void CreateHuman_NullHumanRoleId_Allowed_ReturnsMessageWithNullSenderRoleId()
    {
        ChatRoomMessage message = ChatRoomMessage.CreateHuman("content", null!, "角色名");

        Assert.IsNull(message.SenderRoleId);
        Assert.AreEqual("角色名", message.SenderRoleName);
        Assert.IsTrue(message.IsHumanMessage);
    }

    [TestMethod]
    public void CreateHuman_NullHumanRoleName_Allowed_ReturnsMessageWithNullSenderRoleName()
    {
        ChatRoomMessage message = ChatRoomMessage.CreateHuman("content", "role-id", null!);

        Assert.AreEqual("role-id", message.SenderRoleId);
        Assert.IsNull(message.SenderRoleName);
        Assert.IsTrue(message.IsHumanMessage);
    }

    [TestMethod]
    public void CreateHuman_EmptyContent_ReturnsMessageWithEmptyContent()
    {
        const string content = "";

        ChatRoomMessage message = ChatRoomMessage.CreateHuman(content, "roleId", "roleName");

        Assert.AreEqual(content, message.Content);
        Assert.IsTrue(message.IsHumanMessage);
    }

    [TestMethod]
    public void CreateAssistant_ValidContentAndRoleIdAndRoleName_ReturnsAssistantMessageWithCorrectProperties()
    {
        const string content = "你好，我是助手。";
        const string roleId = "assistant-001";
        const string roleName = "小助手";

        ChatRoomMessage message = ChatRoomMessage.CreateAssistant(content, roleId, roleName);

        Assert.AreEqual(content, message.Content);
        Assert.AreEqual(roleId, message.SenderRoleId);
        Assert.AreEqual(roleName, message.SenderRoleName);
        Assert.IsFalse(message.IsHumanMessage);
        Assert.IsFalse(message.IsSystemMessage);
        Assert.IsNotNull(message.MessageId);
        Assert.AreNotEqual(string.Empty, message.MessageId);
    }

    [TestMethod]
    public void CreateAssistant_NullContent_ThrowsArgumentNullException()
    {
        Assert.ThrowsExactly<ArgumentNullException>(
            () => ChatRoomMessage.CreateAssistant(null!, "roleId", "roleName"));
    }

    [TestMethod]
    public void CreateAssistant_NullRoleId_Allowed_ReturnsMessageWithNullSenderRoleId()
    {
        ChatRoomMessage message = ChatRoomMessage.CreateAssistant("content", null!, "角色名");

        Assert.IsNull(message.SenderRoleId);
        Assert.AreEqual("角色名", message.SenderRoleName);
        Assert.IsFalse(message.IsHumanMessage);
        Assert.IsFalse(message.IsSystemMessage);
    }

    [TestMethod]
    public void CreateAssistant_NullRoleName_Allowed_ReturnsMessageWithNullSenderRoleName()
    {
        ChatRoomMessage message = ChatRoomMessage.CreateAssistant("content", "role-id", null!);

        Assert.AreEqual("role-id", message.SenderRoleId);
        Assert.IsNull(message.SenderRoleName);
        Assert.IsFalse(message.IsHumanMessage);
        Assert.IsFalse(message.IsSystemMessage);
    }

    [TestMethod]
    public void CreateAssistant_EmptyContent_ReturnsMessageWithEmptyContent()
    {
        const string content = "";

        ChatRoomMessage message = ChatRoomMessage.CreateAssistant(content, "roleId", "roleName");

        Assert.AreEqual(content, message.Content);
        Assert.IsFalse(message.IsHumanMessage);
        Assert.IsFalse(message.IsSystemMessage);
    }
}
