//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 个人信息数据库 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sql() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("个人信息数据库.sql", typeof(sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 use grxx;--切换数据库
        ///create table temp
        ///(
        ///   id int ,
        ///   name nchar(10) ,--通讯人姓名
        ///   contact nchar(10),--联系方式
        ///   naddress nchar(10),--工作地点
        ///   city nchar(10),--城市
        ///   comment  nchar(10)--备注
        ///); 的本地化字符串。
        /// </summary>
        internal static string 创建temp {
            get {
                return ResourceManager.GetString("创建temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --1.创建一个数据库
        ///--create database School;
        ///----删除数据库
        ///--drop database School;
        ///--创建数据库的时候指定一些选项。
        ///create database grxx
        ///on primary
        ///(
        ///	name=&apos;grxx&apos;,
        ///	filename=&apos;C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\grxx.mdf&apos;,
        ///	size=5MB,
        ///	filegrowth=10MB,	
        ///	maxsize=100MB
        ///)
        ///log on
        ///(
        ///	name=&apos;grxx_log&apos;,
        ///	filename=&apos;C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\grxx.ldf&apos;,
        ///	size=3MB,
        ///	filegrowth=3%,
        ///	maxsize=20MB
        ///) 的本地化字符串。
        /// </summary>
        internal static string 创建数据库grxx {
            get {
                return ResourceManager.GetString("创建数据库grxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        /// 东城区 
        /// 西城区 
        /// 崇文区 
        /// 宣武区 
        /// 朝阳区 
        /// 丰台区 
        /// 石景山区 
        /// 海淀区 
        /// 门头沟区 
        /// 房山区 
        /// 通州区 
        /// 顺义区 
        /// 昌平区 
        /// 大兴区 
        /// 怀柔区 
        /// 平谷区 
        /// 密云县 
        /// 延庆县 
        ///
        /// 黄浦区 
        /// 卢湾区 
        /// 徐汇区 
        /// 长宁区 
        /// 静安区 
        /// 普陀区 
        /// 闸北区 
        /// 虹口区 
        /// 杨浦区 
        /// 闵行区 
        /// 宝山区 
        /// 嘉定区 
        /// 浦东新区 
        /// 金山区 
        /// 松江区 
        /// 青浦区 
        /// 南汇区 
        /// 奉贤区 
        /// 崇明县 
        ///
        /// 和平区 
        /// 河东区 
        /// 河西区 
        /// 南开区 
        /// 河北区 
        /// 红桥区 
        /// 塘沽区 
        /// 汉沽区 
        /// 大港区 
        /// 东丽区 
        /// 西青区 
        /// 津南区 
        /// 北辰区 
        /// 武清区 
        /// 宝坻区 
        /// 宁河县 
        /// 静海县 
        /// 蓟县 
        ///
        /// 万州区 
        /// 涪陵区 
        /// 渝中区 
        /// 大渡口区 
        /// 江北区 
        /// 沙坪坝区 
        /// 九龙坡区 
        /// 南岸区 
        /// 北碚区 
        /// 万盛区 
        /// 双桥区 
        /// 渝北区 
        /// 巴南区 
        /// 黔江区 
        /// 长寿区 
        /// 江津区 
        /// 合 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 城市 {
            get {
                return ResourceManager.GetString("城市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 use grxx
        ///insert into temp(id,name,contact,naddress,city,comment)
        ///values(&apos;3&apos;,&apos;黄林&apos;,&apos;1&apos;,&apos;中国&apos;,&apos; &apos;,&apos; &apos;);
        /// 的本地化字符串。
        /// </summary>
        internal static string 插入数据 {
            get {
                return ResourceManager.GetString("插入数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --切换数据库
        ///--use grxx;
        ///
        ///
        ///----在grxx数据库中创建addressBook。addressBook
        ///--create table addressBook
        ///--(
        ///--	--表中列的定义在这对小括号中
        ///--	tsid int 
        ///	
        ///--)
        /// 的本地化字符串。
        /// </summary>
        internal static string 表 {
            get {
                return ResourceManager.GetString("表", resourceCulture);
            }
        }
    }
}
