// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsingHardLinkToZipNtfsDiskSize;

#nullable disable

namespace UsingHardLinkToZipNtfsDiskSize.Migrations
{
    [DbContext(typeof(FileStorageContext))]
    [Migration("20231120092807_Lindexi")]
    partial class Lindexi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("UsingHardLinkToZipNtfsDiskSize.FileRecordModel", b =>
                {
                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileSha1Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FilePath");

                    b.ToTable("FileRecordModel");
                });

            modelBuilder.Entity("UsingHardLinkToZipNtfsDiskSize.FileStorageModel", b =>
                {
                    b.Property<string>("FileSha1Hash")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileSha1Hash");

                    b.ToTable("FileStorageModel");
                });
#pragma warning restore 612, 618
        }
    }
}
