<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XiaoXiIme.Foundation\XiaoXiIme.Foundation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sources\xiaoxiime-project-terms.phonetic.tsv">
      <LogicalName>XiaoXiIme.Dictionary.xiaoxiime-project-terms.phonetic.tsv</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
