// <auto-generated />
using System;
using FayawlerjiraywereNiharjeechel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FayawlerjiraywereNiharjeechel.Migrations
{
    [DbContext(typeof(FayawlerjiraywereNiharjeechelContext))]
    [Migration("20190611012522_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1");

            modelBuilder.Entity("FayawlerjiraywereNiharjeechel.Controllers.VisitingCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ip");

                    b.Property<DateTime>("Time");

                    b.Property<string>("UserAgent");

                    b.HasKey("Id");

                    b.ToTable("VisitingCount");
                });
#pragma warning restore 612, 618
        }
    }
}
