//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightTextEditorPlus.Resources.Skia {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightTextEditorPlus.Resources.Skia.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当 RelativeUnit 为 Relative 时，坐标值必须在 [0, 1] 范围内。 的本地化字符串。
        /// </summary>
        internal static string GradientSkiaTextBrushRelativePoint_RelativeCoordinateMustBeInRange {
            get {
                return ResourceManager.GetString("GradientSkiaTextBrushRelativePoint_RelativeCoordinateMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的 CharData 不在当前的 LineDrawingArgument 中，不能用于获取四线格信息。 的本地化字符串。
        /// </summary>
        internal static string RenderManagerExtension_CharDataMustBelongToCurrentLine {
            get {
                return ResourceManager.GetString("RenderManagerExtension_CharDataMustBelongToCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一行内存在多个不同的字符属性时，必须传入 CharData 以指定使用哪个字符属性信息。 的本地化字符串。
        /// </summary>
        internal static string RenderManagerExtension_MustSpecifyCharDataWhenMultipleRunPropertiesExist {
            get {
                return ResourceManager.GetString("RenderManagerExtension_MustSpecifyCharDataWhenMultipleRunPropertiesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量完成后，必然能够获取当前字符的尺寸。 的本地化字符串。
        /// </summary>
        internal static string SkiaCharInfoMeasurer_CurrentCharSizeMustBeAvailableAfterMeasure {
            get {
                return ResourceManager.GetString("SkiaCharInfoMeasurer_CurrentCharSizeMustBeAvailableAfterMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 {0} 只有在调试模式下才能调用。 的本地化字符串。
        /// </summary>
        internal static string SkiaTextEditor_DebugReRenderOnlyAvailableInDebugMode {
            get {
                return ResourceManager.GetString("SkiaTextEditor_DebugReRenderOnlyAvailableInDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个 SkiaTextEditorPlatformProvider 只能和一个 SkiaTextEditor 关联，禁止跨文本框复用。当前传入的平台提供器已关联文本框，DebugName={0}。 的本地化字符串。
        /// </summary>
        internal static string SkiaTextEditor_PlatformProviderAlreadyBoundToTextEditor {
            get {
                return ResourceManager.GetString("SkiaTextEditor_PlatformProviderAlreadyBoundToTextEditor", resourceCulture);
            }
        }
    }
}
